#!/bin/bash
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR
echo `date` > last-run-started

git fetch origin
git checkout origin/master

echo 'HERE!'
python crfuchbot.py > last-output
echo 'HERE2!'

cd $DIR
echo `date` > last-run-finished
